### ISSUE TITLE
Prepare for import in EDPOP

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/edpop-explorer#9]
Expand the package to work as the definition of our catalogi that can be imported in de EDPOP backend.

We roughly imagine the following structure, which mostly matches what we have.

- A general `Reader` class
- Subclasses of `Reader` designed for different types of catalogi, e.g. `RDFReader`, `SruMarcReader`, etc.
- A subclass for each catalogus we want to include in EDPOP, e.g. `HPBReader`, `GallicaReader`, etc.

Readers have methods for querying and converting results that depend on the catalogus, though the API should be scaffolded in `Reader`.

**Comment by tijmenbaarda** [comment]
Any thoughts for a new name for `edpop-explorer`?

**Comment by jgonggrijp** [comment]
I was thinking of `edpop-catalog(s)`, but didn't mention it yet because I wanted to try to come up with more ideas. So far, I've been inspirationless.

**Comment by tijmenbaarda** [comment]
This has been done by now
